[package]
name = "rsdsl"
version = "0.1.0"
edition = "2021"

[dependencies]
rsdsl_macros = { path = "../rsdsl_macros" }
regex = "1"
thiserror = "1"
serde = { version = "1", features = ["derive"], optional = true }
